### ISSUE TITLE
how to model a "at least one" check

### ISSUE THREAD

**Issue by dberardo** [benprew/nagios-checks#17]
Hi,

the script works fine to monitor that all servers behind a backend are UP. but what if i want only to check that AT LEAST one server is UP?

HAproxy provides already this check, since the backend status is UP if at least on of the server in its group is UP, and becomes DOWN if this is not the case.

How can this ruby script be adapted / configured to achieve this check?

**Comment by dberardo** [comment]
fixed in https://github.com/benprew/nagios-checks/pull/18

**Comment by benprew** [comment]
@dberardo Thanks for raising this issue, it is similar to issue #14, where a backup server is listed at DOWN shouldn't cause a CRITICAL error.  I put together a fix for this and 14 in PR #19 .  Can you test with the updated version of check_haproxy.rb to see if that fixes your issue?  If not, can you send an example haproxy .csv file I could use to test against?

Thanks

**Comment by dberardo-com** [comment]
for the moment, the changes proposed in #18 are already "fixing the issue" for my use case. I could however give a try at the proposed changes in #19  as well. Hopefully this week still.
