### ISSUE TITLE
Error in ruby 2.7.0

### ISSUE THREAD

**Issue by CHRT3** [benprew/nagios-checks#20]
check_haproxy_stats.rb:134: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/open-uri.rb:13: warning: The called method `open' is defined here
check_haproxy_stats.rb:134: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

Try to get rid of the error above. You need a change in line 134:

return open(options.url, open_options(options)) to return open.URI(options.url, **open_options(options))

**Comment by benprew** [comment]
Hi @CHRT3 thanks for the note.  This should be fixed now.  Let me know if it's not.
