### ISSUE TITLE
Error in Rhel 7 Ruby 2.0

### ISSUE THREAD

**Issue by brvolpini** [benprew/nagios-checks#7]
Hi,
I have an issue executing the script on the nagios server. That´s what i do:

/usr/lib64/nagios/plugins/check_haproxy.rb -u http://xxx.xxx.xxx.xxx:port
And the output is:

/usr/lib64/nagios/plugins/check_haproxy.rb:162:in `/': divided by 0 (ZeroDivisionError)
        from /usr/lib64/nagios/plugins/check_haproxy.rb:162:in`block in <main>'
        from /usr/lib64/nagios/plugins/check_haproxy.rb:98:in `each'
        from /usr/lib64/nagios/plugins/check_haproxy.rb:98:in`<main>'

Greetings.

**Comment by pulecp** [comment]
You can try my fix.

The issue is that this plugin tries to calculate session statistics even when there was no session in total so far.

**Comment by pulecp** [comment]
one more condition

**Comment by benprew** [comment]
@pulecp This is great, thanks for contributing to this project!  I had a few comments on your pull request, get them fixed up and I'll merge it.  Thanks again for your help, I really appreciate it!

**Comment by benprew** [comment]
#8 fixes this issue.

**Comment by benprew** [comment]
@pulecp Thanks again for your changes, I've finally had a chance to review and merge them.
